#ifndef UTF8_HPP
#define UTF8_HPP

/**
 * @file Utf8.hpp
 *
 * This module declares the Utf8::Utf8 class.
 *
 * © 2018 by Richard Walters
 */

#include <memory>
#include <stdint.h>
#include <string>
#include <ostream>
#include <vector>

namespace Utf8 {

    /**
     * This represents a single character in Unicode.
     */
    typedef uint32_t UnicodeCodePoint;

    /**
     * This function is for convenience, converting a given ASCII string
     * into its equivalent sequence of Unicode code points.
     *
     * @param[in] ascii
     *     This is the ASCII string to convert.
     *
     * @return
     *     The Unicode code points for the given ASCII string are returned.
     */
    std::vector< UnicodeCodePoint > AsciiToUnicode(const std::string& ascii);

    /**
     * This class is used to encode or decode Unicode "code points",
     * or characters from many different international character sets,
     * in order to store or transmit them across any interface
     * that accepts a sequence of bytes.
     */
    class Utf8 {
        // Lifecycle management
    public:
        ~Utf8() noexcept;
        Utf8(const Utf8&) = delete;
        Utf8(Utf8&&) noexcept = delete;
        Utf8& operator=(const Utf8&) = delete;
        Utf8& operator=(Utf8&&) noexcept = delete;

        // Public methods
    public:
        /**
         * This is the default constructor.
         */
        Utf8();

        /**
         * This method encodes the given sequence of Unicode code
         * points into UTF-8.
         *
         * @param[in] codePoints
         *     These are the Unicode code points to encode.
         *
         * @return
         *     The UTF-8 encoding of the given Unicode code points is returned.
         */
        static std::vector< uint8_t > Encode(const std::vector< UnicodeCodePoint >& codePoints);

        /**
         * This method accepts the given sequence of UTF-8 encoded bytes,
         * and returns any Unicode code points formed from them.
         *
         * Any partial code sequence at the end is held onto and used first
         * when this method is called again later.
         *
         * This overload accepts a vector of bytes.
         *
         * @param[in] encoding
         *     This is the sequence of UTF-8 encoded bytes to shift into
         *     the decoder.
         *
         * @return
         *     All Unicode code points generated by the decoder are returned.
         */
        std::vector< UnicodeCodePoint > Decode(const std::vector< uint8_t >& encoding);

        /**
         * This method accepts the given sequence of UTF-8 encoded bytes,
         * and returns any Unicode code points formed from them.
         *
         * Any partial code sequence at the end is held onto and used first
         * when this method is called again later.
         *
         * This overload accepts a C++ string.
         *
         * @param[in] encoding
         *     This is the sequence of UTF-8 encoded bytes to shift into
         *     the decoder.
         *
         * @return
         *     All Unicode code points generated by the decoder are returned.
         */
        std::vector< UnicodeCodePoint > Decode(const std::string& encoding);

        /**
         * This method accepts the given sequence of UTF-8 encoded bytes,
         * and returns an indication of whether or not the encoding is valid.
         *
         * @param[in] encoding
         *     This is the sequence of UTF-8 encoded bytes to shift into
         *     the decoder.
         *
         * @param[in] final
         *     This flag indicates whether or not this is the end of the
         *     encoding.  If it is not, any partial code sequence at the end
         *     is held onto and used first when this method is called
         *     again later.
         *
         * @return
         *     An indication of whether or not the encoding is valid
         *     is returned.
         */
        bool IsValidEncoding(
            const std::string& encoding,
            bool final = true
        );

        // Private properties
    private:
        /**
         * This is the type of structure that contains the private
         * properties of the instance.  It is defined in the implementation
         * and declared here to ensure that it is scoped inside the class.
         */
        struct Impl;

        /**
         * This contains the private properties of the instance.
         */
        std::unique_ptr< Impl > impl_;
    };

}

#endif /* UTF8_HPP */
